# Introduction to NumPy


The learning objectives of this section are:

* Understand advantages of vectorised code using NumPy (over standard python ways)
* Create NumPy arrays
    * Convert lists and tuples to NumPy arrays 
    * Create (initialise) arrays
* Inspect the structure and content of arrays
* Subset, slice, index and iterate through arrays
* Compare computation times in NumPy and standard Python lists

### NumPy Basics

NumPy is a library written for scientific computing and data analysis. It stands for numerical python.

The most basic object in NumPy is the ```ndarray```, or simply an ```array```, which is an **n-dimensional, homogenous** array. By homogenous, we mean that all the elements in a NumPy array have to be of the **same data type**, which is commonly numeric (float or integer). 

Let's see some examples of arrays.

In [2]:
# Import the numpy library
# np is simply an alias, you may use any other alias, though np is quite standard
import numpy as np

In [7]:
np_array1= np.array((5, 5, 'test', 'it contains', 9.6))
print(np_array1)
print()
print(type(np_array1))
print()
print(np_array1.shape)


['5' '5' 'test' 'it contains' '9.6']

<class 'numpy.ndarray'>

(5,)


In [8]:
# Creating a 1-D array using a list
# np.array() takes in a list or a tuple as argument, and converts into an array
array_1d = np.array([2, 4, 5, 6, 7, 9])
print(array_1d)
print(type(array_1d))

[2 4 5 6 7 9]
<class 'numpy.ndarray'>


In [10]:
ary_1d= np.array((1,5,6,6))
print(ary_1d)

[1 5 6 6]


In [11]:
# Creating a 2-D array using two lists
array_2d = np.array([[2, 3, 4], [5, 8, 7]])
print(array_2d)

[[2 3 4]
 [5 8 7]]


In NumPy, dimensions are called **axes**. In the 2-d array above, there are two axes, having two and three elements respectively. 

In NumPy terminology, for 2-D arrays:
* ```axis = 0``` refers to the rows
* ```axis = 1``` refers to the columns

<img src="numpy_axes.jpg" style="width: 600px; height: 400px">

### Advantages of NumPy 

What is the use of arrays over lists, specifically for data analysis? Putting crudely, it is **convenience and speed **:<br>
1. You can write **vectorised** code on numpy arrays, not on lists, which is **convenient to read and write, and concise**. 
2. Numpy is **much faster** than the standard python ways to do computations.

Vectorised code typically does not contain explicit looping and indexing etc. (all of this happens behind the scenes, in precompiled C-code), and thus it is much more concise.

Let's see an example of convenience, we'll see one later for speed. 

Say you have two lists of numbers, and want to calculate the element-wise product. The standard python list way would need you to map a lambda function (or worse - write a ```for``` loop), whereas with NumPy, you simply multiply the arrays.

In [12]:
list_1 = [3, 6, 7, 5]
list_2 = [4, 5, 1, 7]

# the list way to do it: map a function to the two lists
product_list = list(map(lambda x, y: x*y, list_1, list_2))
print(product_list)


[12, 30, 7, 35]


In [13]:
tuple_1 = (5, 7, 9, 6)
tuple_2 = (4, 5, 6, 7)
print([x*y for x,y in zip(tuple_1, tuple_2)])

[20, 35, 54, 42]


In [15]:
# The numpy array way to do it: simply multiply the two arrays
import numpy as np
array_1 = np.array(list_1)
array_2 = np.array(list_2)

array_3 = array_1*array_2
print(array_3)
print(type(array_3))

[12 30  7 35]
<class 'numpy.ndarray'>


In [16]:
array_11 = np.array(tuple_1)
array_22 = np.array(tuple_2)
array_33 = array_11*array_22
print(array_33)

[20 35 54 42]


As you can see, the NumPy way is clearly more concise.

Even simple mathematical operations on lists require for loops, unlike with arrays. For example, to calculate the square of every number in a list:

In [17]:
# Square a list
list_squared = [i**2 for i in list_1]

# Square a numpy array
array_squared = array_1**2

print(list_squared)
print(array_squared)

[9, 36, 49, 25]
[ 9 36 49 25]


In [18]:
print(type(array_2))

<class 'numpy.ndarray'>


In [19]:
np_array_squared = array_2**2
print(np_array_squared)

[16 25  1 49]


In [20]:
print(np.__version__)

1.21.5


This was with 1-D arrays. You'll often work with 2-D arrays (matrices), where the difference would be even greater. With lists, you'll have to store matrices as lists of lists and loop through them. With NumPy, you simply multiply the matrices.

### Creating NumPy Arrays 

There are multiple ways to create numpy arrays, the most commmon ones being:
* Convert lists or tuples to arrays using ```np.array()```, as done above
* Initialise arrays of fixed size (when the size is known) 


In [22]:
# Convert lists or tuples to arrays using np.array()
# Note that np.array(2, 5, 6, 7) will throw an error - you need to pass a list or a tuple
array_from_list = np.array([2, 5, 6, 7]) 
array_from_tuple = np.array((4, 5, 8, 9))

print(array_from_list)
print(array_from_tuple)

[2 5 6 7]
[4 5 8 9]


The other common way is to initialise arrays. You do this when you know the size of the array beforehand.

The following ways are commonly used:
* ```np.ones()```: Create array of 1s
* ```np.zeros()```: Create array of 0s
* ```np.random.random()```: Create array of random numbers
* ```np.arange()```: Create array with increments of a fixed step size
* ```np.linspace()```: Create array of fixed length

In [44]:
# Tip: Use help to see the syntax when required
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionadded:: 1.20

In [23]:
# Creating a 5 x 3 array of ones
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.zeros((3,5), complex)

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [25]:
np.ones((6,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [26]:
# Notice that, by default, numpy creates data type = float64
# Can provide dtype explicitly using dtype
np.ones((5, 3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [29]:
# Creating array of zeros
np.zeros(4, dtype = int)

array([0, 0, 0, 0])

In [31]:
print(np.zeros(4, dtype=int))

[0 0 0 0]


In [12]:
# Array of random numbers
np.random.random([3, 4])

array([[0.21067268, 0.20062275, 0.9481293 , 0.37904343],
       [0.28643457, 0.26614814, 0.43219753, 0.63020881],
       [0.36568786, 0.37602622, 0.85852183, 0.29602912]])

In [32]:
np.random.random(size=[4,6])

array([[0.59675724, 0.14234544, 0.59276248, 0.90534221, 0.36286691,
        0.65055368],
       [0.58514647, 0.2131628 , 0.89549629, 0.00207786, 0.50637517,
        0.21331601],
       [0.74092473, 0.2419757 , 0.29281002, 0.27925944, 0.0277561 ,
        0.42922059],
       [0.51223028, 0.9135011 , 0.62720891, 0.04232665, 0.61828432,
        0.10142541]])

In [38]:
np.random.random([4])*10 # (0.0, 1.0)

array([2.39718043, 2.7974904 , 9.27277654, 6.50460719])

In [43]:
np.random.random(10)

array([0.00896778, 0.63992998, 0.61340901, 0.3939414 , 0.8397532 ,
       0.01620074, 0.61009884, 0.71101225, 0.33244034, 0.38149781])

In [45]:
np.random.choice(['dfas', 'dfasdf', 'fffffdfff' 'dfsdaf', 'dfasdfdfd', 'fdgdf'])

'fdgdf'

In [48]:
deck = 'ace two three four'.split()
np.random.shuffle(deck)                        # Shuffle a list
deck

['two', 'ace', 'three', 'four']

In [49]:
#np.arange()
# np.arange() is the numpy equivalent of range()
# Notice that 10 is included, 100 is not, as in standard python lists

# From 10 to 100 with a step of 5
numbers = np.arange(10, 100, 5)
print(numbers)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [50]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [51]:
[num for num in range(5)]

[0, 1, 2, 3, 4]

In [52]:
# np.linspace()
# Sometimes, you know the length of the array, not the step size

# Array of length 25 between 15 and 18
np.linspace(15, 18, 25)

array([15.   , 15.125, 15.25 , 15.375, 15.5  , 15.625, 15.75 , 15.875,
       16.   , 16.125, 16.25 , 16.375, 16.5  , 16.625, 16.75 , 16.875,
       17.   , 17.125, 17.25 , 17.375, 17.5  , 17.625, 17.75 , 17.875,
       18.   ])

In [53]:
np.linspace(2, 10, 4)

array([ 2.        ,  4.66666667,  7.33333333, 10.        ])

In [55]:
np.linspace( 4, 15, 34)

array([ 4.        ,  4.33333333,  4.66666667,  5.        ,  5.33333333,
        5.66666667,  6.        ,  6.33333333,  6.66666667,  7.        ,
        7.33333333,  7.66666667,  8.        ,  8.33333333,  8.66666667,
        9.        ,  9.33333333,  9.66666667, 10.        , 10.33333333,
       10.66666667, 11.        , 11.33333333, 11.66666667, 12.        ,
       12.33333333, 12.66666667, 13.        , 13.33333333, 13.66666667,
       14.        , 14.33333333, 14.66666667, 15.        ])

Apart from the methods mentioned above, there are a few more NumPy functions that you can use to create special NumPy arrays:

-  `np.full()`: Create a constant array of any number ‘n’
-  `np.tile()`: Create a new array by repeating an existing array for a particular number of times
-  `np.eye()`: Create an identity matrix of any dimension
-  `np.randint()`: Create a random array of integers within a particular range

In [56]:
# Creating a 4 x 3 array of 7s using np.full()
# The default data type here is int only
np.full((4,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [57]:
np.full((5,2), [9.8, 5])

array([[9.8, 5. ],
       [9.8, 5. ],
       [9.8, 5. ],
       [9.8, 5. ],
       [9.8, 5. ]])

In [58]:
# Given an array, np.tile() creates a new array by repeating the given array for any number of times that you want
# The default data type her is int only
arr = ([0, 1, 2])
np.tile(arr, 3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [59]:
# You can also create multidimensional arrays using np.tile()
np.tile(arr, (3,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [60]:
# Create a 3 x 3 identity matrix using np.eye()
# The default data type here is float. So if we want integer values, we need to specify the dtype to be int
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [61]:
np.eye(5, dtype=complex)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [92]:
# Create a 4 x 4 random array of integers ranging from 0 to 9
np.random.randint(0, 10, (4,4))

array([[6, 3, 4, 8],
       [2, 6, 8, 9],
       [0, 4, 8, 4],
       [2, 0, 5, 0]])

In [63]:
print(np.random.randint(1, 5, size =(3,4)))

[[1 3 2 1]
 [1 3 4 2]
 [3 4 4 1]]


In [64]:
np.random.randint(5, 14, (5,3))

array([[13,  5,  6],
       [12,  5,  6],
       [ 6,  5, 13],
       [13,  9,  6],
       [ 6, 10, 13]])

### Inspect the Structure and Content of Arrays

It is helpful to inspect the structure of numpy arrays, especially while working with large arrays. Some attributes of numpy arrays are:
* ```shape```: Shape of array (n x m)
* ```dtype```: data type (int, float etc.)
* ```ndim```: Number of dimensions (or axes)
* ```itemsize```: Memory used by each array elememnt in bytes


Let's say you are working with a moderately large array of size 1000 x 300. First, you would want to wrap your head around the basic shape and size of the array. 

In [65]:
# Initialising a random 1000 x 300 array
rand_array = np.random.random((1000, 300))

# Print the second row
print(rand_array[1, ])

[8.15592500e-01 2.85603538e-02 1.24571850e-01 5.48653084e-01
 8.47922034e-01 3.46672698e-01 4.59514957e-01 5.02967071e-01
 7.13053349e-01 3.40886081e-01 8.13804052e-02 7.39543178e-01
 1.26010935e-01 1.23741330e-01 5.61508226e-01 2.62530879e-01
 3.50897417e-01 8.73341090e-01 9.87412430e-01 7.95859487e-01
 4.26391126e-01 2.70481644e-01 9.60849087e-01 5.63933274e-01
 7.52224823e-01 3.66016976e-01 3.18843183e-01 1.15177003e-01
 8.21325361e-01 7.00247258e-01 2.91364418e-02 3.89662662e-01
 9.17494750e-01 9.03794309e-01 8.92009760e-02 6.70688441e-01
 2.24666775e-01 3.67661471e-01 6.02645159e-01 8.47459204e-01
 3.20349310e-01 6.92285690e-01 4.47244793e-01 7.60193243e-01
 3.25124215e-01 4.81002120e-01 2.25715826e-01 7.11591253e-01
 7.44771917e-01 3.59469900e-01 8.86162573e-01 5.28807723e-01
 5.92892415e-01 6.91769667e-01 3.31134090e-01 3.92840248e-02
 2.61719808e-01 6.48119588e-01 8.42395846e-01 4.11067299e-01
 6.44601890e-01 1.92801300e-01 5.13350729e-01 1.78949352e-01
 2.10807364e-01 4.516881

In [66]:
rand_float= np.random.random((20, 23))
print(rand_float[1,])

[0.20448194 0.88132484 0.8173897  0.71370326 0.41378339 0.28555678
 0.75935857 0.15532587 0.97223106 0.20351687 0.70872784 0.70882316
 0.98990566 0.72672676 0.29658912 0.07904351 0.9913624  0.48738745
 0.92337387 0.37965196 0.73889458 0.97890714 0.7506853 ]


In [68]:
# Inspecting shape, dtype, ndim and itemsize
print("Shape: {}".format(rand_array.shape))
print("dtype: {}".format(rand_array.dtype))
print("Dimensions: {}".format(rand_array.ndim))
print("Item size: {}".format(rand_array.itemsize))

Shape: (1000, 300)
dtype: float64
Dimensions: 2
Item size: 8


Reading 3-D arrays is not very obvious, because we can only print maximum two dimensions on paper, and thus they are printed according to a specific convention. Printing higher dimensional arrays follows the following conventions:
* The last axis is printed from left to right
* The second-to-last axis is printed from top to bottom
* The other axes are also printed top-to-bottom, with each slice separated by another using an empty line 

Let's see some examples.

In [69]:
array_3dim= np.arange(30)
array_3dim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [111]:
array_3dim.reshape(2, 3, 5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [71]:
# Creating a 3-D array
# reshape() simply reshapes a 1-D array 
array_3d = np.arange(24).reshape(2, 3, 4)
print(array_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


* The last axis has 4 elements, and is printed from left to right.
* The second last has 3, and is printed top to bottom
* The other axis has 2, and is printed in the two separated blocks

### Subset, Slice, Index and Iterate through Arrays

For **one-dimensional arrays**, indexing, slicing etc. is **similar to python lists** - indexing starts at 0.

In [73]:
# Indexing and slicing one dimensional arrays
array_1d = np.arange(4, 20, 2)
print(array_1d)

[ 4  6  8 10 12 14 16 18]


In [126]:
array_1d[3] # element at index 3

10

In [132]:
# Specific elements
# Notice that array[2, 5, 6] will throw an error, you need to provide the indices as a list
print(array_1d[[2, 5, 6]])
print(array_1d[[3,4,6]])

[ 8 14 16]
[10 12 16]


In [74]:
list1 = [num for num in range(5, 15)]
list1

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [80]:
list1[]

TypeError: list indices must be integers or slices, not list

In [143]:
# Slice third element onwards 
print(array_1d[2:])

[ 8 10 12 14 16 18]


In [144]:
# Slice first three elements
print(array_1d[:3])


[4 6 8]


In [145]:
print(array_1d[:5])

[ 4  6  8 10 12]


In [146]:
# Slice third to seventh elements
print(array_1d[2:7])

[ 8 10 12 14 16]


In [148]:
# Subset starting 0 at increment of 2 
# syntax of double colon(::) [start:stop:step]
print(array_1d[0::2])

[ 4  8 12 16]


In [149]:
# Third element
print(array_1d[2])

# Specific elements
# Notice that array[2, 5, 6] will throw an error, you need to provide the indices as a list
print(array_1d[[2, 5, 6]])

# Slice third element onwards
print(array_1d[2:])

# Slice first three elements
print(array_1d[:3])

# Slice third to seventh elements
print(array_1d[2:7])

# Subset starting 0 at increment of 2 
print(array_1d[0::2])

8
[ 8 14 16]
[ 8 10 12 14 16 18]
[4 6 8]
[ 8 10 12 14 16]
[ 4  8 12 16]


In [152]:
# Iterations are also similar to lists
for i in array_1d:
    print(i**2)

16
36
64
100
144
196
256
324


In [154]:
print([element**2 for element in array_1d])

[16, 36, 64, 100, 144, 196, 256, 324]


In [163]:
nd_array = np.random.random(20).reshape(4,5)
print(nd_array)
print(type(nd_array))
print(nd_array.shape)

[[0.33580133 0.5497621  0.34546401 0.67824906 0.33366158]
 [0.57581821 0.77653734 0.07643149 0.57100065 0.52872014]
 [0.44114173 0.98203152 0.63602903 0.22306199 0.19432412]
 [0.71979685 0.05462616 0.86701747 0.99613082 0.0851517 ]]
<class 'numpy.ndarray'>
(4, 5)


**Multidimensional arrays** are indexed using as many indices as the number of dimensions or axes. For instance, to index a 2-D array, you need two indices - ```array[x, y]```. 

Each axes has an index starting at 0. The following figure shows the axes and their indices for a 2-D array.

<img src="2_d_array.png" style="width: 350px; height: 300px">


In [165]:
# Creating a 2-D array
array_2d = np.array([[2, 5, 7, 5], [4, 6, 8, 10], [10, 12, 15, 19]])
print(array_2d)

[[ 2  5  7  5]
 [ 4  6  8 10]
 [10 12 15 19]]


In [169]:
# Third row second column
print(array_2d[2, 1])
print(type(array_2d[2,1]))

12
<class 'numpy.int32'>


In [170]:
# Slicing the second row, and all columns
# Notice that the resultant is itself a 1-D array
print(array_2d[1, :])
print(type(array_2d[1, :]))

[ 4  6  8 10]
<class 'numpy.ndarray'>


In [171]:
# Slicing all rows and the third column
print(array_2d[:, 2])
print(type(array_2d[:,2]))

[ 7  8 15]
<class 'numpy.ndarray'>


In [174]:
# Slicing all rows and the first three columns
print(array_2d[:, :3])

[[ 2  5  7]
 [ 4  6  8]
 [10 12 15]]


In [175]:
print(array_2d)

[[ 2  5  7  5]
 [ 4  6  8 10]
 [10 12 15 19]]


In [184]:
print(array_2d[:, :2])

[[ 2  5]
 [ 4  6]
 [10 12]]


**Iterating on 2-D arrays** is done with respect to the first axis (which is row, the second axis is column). 

In [185]:
# Iterating over 2-D arrays
for row in array_2d:
    print(row)

[2 5 7 5]
[ 4  6  8 10]
[10 12 15 19]


In [193]:
for row in array_2d:
    for item in row:
        print(item)

2
5
7
5
4
6
8
10
10
12
15
19


In [194]:
# Iterating over 3-D arrays: Done with respect to the first axis
array_3d = np.arange(24).reshape(2, 3, 4)
print(array_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [202]:
array_3d = np.arange(2, 122, 2)
print(array_3d)
print(type(array_3d))
print(array_3d.shape)
array_3d.reshape(4,5,3)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120]
<class 'numpy.ndarray'>
(60,)


array([[[  2,   4,   6],
        [  8,  10,  12],
        [ 14,  16,  18],
        [ 20,  22,  24],
        [ 26,  28,  30]],

       [[ 32,  34,  36],
        [ 38,  40,  42],
        [ 44,  46,  48],
        [ 50,  52,  54],
        [ 56,  58,  60]],

       [[ 62,  64,  66],
        [ 68,  70,  72],
        [ 74,  76,  78],
        [ 80,  82,  84],
        [ 86,  88,  90]],

       [[ 92,  94,  96],
        [ 98, 100, 102],
        [104, 106, 108],
        [110, 112, 114],
        [116, 118, 120]]])

In [214]:
array_3d[[0:2, 0:3]]

SyntaxError: invalid syntax (3790865758.py, line 1)

In [33]:
# Prints the two blocks
for row in array_3d:
    print(row)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


### Compare Computation Times in NumPy and Standard Python Lists

We mentioned that the key advantages of numpy are convenience and speed of computation. 

You'll often work with extremely large datasets, and thus it is important point for you to understand how much computation time (and memory) you can save using numpy, compared to standard python lists.   

Let's compare the computation times of arrays and lists for a simple task of calculating the element-wise product of numbers. 

In [34]:
## Comparing time taken for computation
list_1 = [i for i in range(1000000)]
list_2 = [j**2 for j in range(1000000)]

# list multiplication
import time

# store start time, time after computation, and take the difference
t0 = time.time()
product_list = list(map(lambda x, y: x*y, list_1, list_2))
t1 = time.time()
list_time = t1 - t0 
print(t1-t0)


# numpy array 
array_1 = np.array(list_1)
array_2 = np.array(list_2)

t0 = time.time()
array_3 = array_1*array_2
t1 = time.time()
numpy_time = t1 - t0

print(t1-t0)

print("The ratio of time taken is {}".format(list_time/numpy_time))

0.13862943649291992
0.00394892692565918
The ratio of time taken is 35.10559681217171


In this case, numpy is **an order of magnitude faster** than lists. This is with arrays of size in millions, but you may work on much larger arrays of sizes in order of billions. Then, the difference is even larger.

Some reasons for such difference in speed are:
* NumPy is written in C, which is basically being executed behind the scenes
* NumPy arrays are more compact than lists, i.e. they take much lesser storage space than lists


The following discussions demonstrate the differences in speeds of NumPy and standard python:
1. https://stackoverflow.com/questions/8385602/why-are-numpy-arrays-so-fast
2. https://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists
