In [30]:
import numpy as np

In [31]:
np_array= np.array([[4,5,7,14], [5,8,9, 4]], float)
np_array

array([[ 4.,  5.,  7., 14.],
       [ 5.,  8.,  9.,  4.]])

In [32]:
print(np_array)
print()
print(type(np_array))
print(np_array.shape)
print(np_array.dtype)

[[ 4.  5.  7. 14.]
 [ 5.  8.  9.  4.]]

<class 'numpy.ndarray'>
(2, 4)
float64


In [33]:
np_array[1, 3]

4.0

In [34]:
np_array2 = np_array[:, 2]
np_array2

array([7., 9.])

In [37]:
np_array.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [38]:
np_array.T

array([[ 4.,  5.],
       [ 5.,  8.],
       [ 7.,  9.],
       [14.,  4.]])

In [39]:
np_array.real

array([[ 4.,  5.,  7., 14.],
       [ 5.,  8.,  9.,  4.]])

In [42]:
np_array.imag

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
for item in np_array.flat:
    print(item)

4.0
5.0
7.0
14.0
5.0
8.0
9.0
4.0


In [46]:
np_array.view(dtype=complex)

array([[4. +5.j, 7.+14.j],
       [5. +8.j, 9. +4.j]])

In [47]:
np.array([1]).shape

(1,)

In [49]:
np.ones((5,6,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [65]:
nd_array = np.arange(start=1, stop=50, step=4, dtype=int)
nd_array

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49])

In [66]:
nd_array.shape

(13,)

In [67]:
nd_array.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [68]:
neg_array = np.arange(7, 0, -10)
neg_array

array([7])

In [69]:
neg_array**2

array([49], dtype=int32)

In [60]:
neg_array.itemsize

4

In [73]:
2** (np.arange(10))

array([  1,   2,   4,   8,  16,  32,  64, 128, 256, 512], dtype=int32)

In [75]:
nd_array = np.array([0, -1, 9, -5, -3, 6])

In [76]:
np.abs(nd_array)

array([0, 1, 9, 5, 3, 6])

In [77]:
np.sin(nd_array)

array([ 0.        , -0.84147098,  0.41211849,  0.95892427, -0.14112001,
       -0.2794155 ])

In [79]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [82]:
>>> import timeit
>>> n = 1
>>> print(timeit.timeit(f'x = [i**2 for i in range({n})]'))
>>> print(timeit.timeit(f'x = np.arange({n})**2', setup='import numpy as np'))

1.385189900000114
3.5024116999993566


In [83]:
>>> import timeit
>>> n = 5
>>> print(timeit.timeit(f'x = [i**2 for i in range({n})]'))
>>> print(timeit.timeit(f'x = np.arange({n})**2', setup='import numpy as np'))

3.3324650000004112
4.393362900000284


In [84]:
np.arange(-8, -2, 2)

array([-8, -6, -4])

In [88]:
np.arange(7, -8, -4)

array([ 7,  3, -1, -5])

In [89]:
np.arange(8, 2)

array([], dtype=int32)

Practice
Description
Create a 3*3 array using list_1 = [1,2,3] list_2 = [4,5,6] list_3 = [7,8,9]

In [93]:
import numpy as np
list_1 = [1,2,3] 
list_2 = [4,5,6] 
list_3 = [7,8,9]

_3by3_array = np.array([list_1, list_2, list_3] )
print(_3by3_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
