In [1]:
import numpy as np
import pandas as pd

In [4]:
np.random.random(10)

array([0.23692   , 0.98612398, 0.9829453 , 0.79326899, 0.79975479,
       0.49243396, 0.06129459, 0.68443852, 0.1769316 , 0.9733306 ])

In [9]:
np.eye(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [13]:
np.sqrt(9)

3.0

In [14]:
np.pi

3.141592653589793

In [15]:
np.sin(np.pi/2)

1.0

In [22]:
arr = np.array([0, 45, 90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

[0.         0.78539816 1.57079633 3.14159265 4.71238898 6.28318531]


In [20]:
np.arcsin(np.pi/4)

0.9033391107665127

In [21]:
1/(np.sqrt(2))

0.7071067811865475

In [23]:
np.sin(0.78539816)

0.7071067787841887

In [24]:
base = 3
perp = 4

x = np.hypot(base, perp)

print(x)

5.0


In [25]:
base = 5
perp = 12

x = np.hypot(base, perp)

print(x)

13.0


In [26]:
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


In [27]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]


In [28]:

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)

[3 4]


In [29]:

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)

[1 2]


In [30]:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)

print(newarr)

[1 2 5 6]


In [31]:
arr = np.arange(1, 10)

print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [32]:

arr = np.arange(1, 10)

print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [35]:
a = np.array([[1,2,3], [4, 5, 6], [7,8,9]])
np.linalg.det(a)

6.66133814775094e-16

In [37]:
a.shape

(3, 3)