In [31]:
import numpy as np
import math
pi= math.pi

In [32]:
money = np.array([2, 0, 1, 1])
hurry = np.array([1, 0, 1, 1])
meeting= np.array([0, 1, 0, 1])
powerpoint= np.array([0, 1, 0, 0])

print(money)
print()
print(hurry)
print()
print(meeting)
print()
print(powerpoint)

[2 0 1 1]

[1 0 1 1]

[0 1 0 1]

[0 1 0 0]


In [33]:
email_1= [2, 1, 0, 0]
email_2= [0, 0, 1, 1]
email_3= [1, 1, 0, 0]
email_4= [1, 1, 1, 0]

In [34]:
dot_prod_email_1_and_email_2 = np.dot(email_1, email_2)
dot_prod_email_1_and_email_2

0

In [69]:
def calculate_mod(email):
    return np.sqrt(np.array([word_count**2 for word_count in email]).sum())

In [70]:
mod_of_email_1 =calculate_mod(email_1)
mod_of_email_1

2.23606797749979

In [71]:
mod_of_email_2 = calculate_mod(email_2)
mod_of_email_2

1.4142135623730951

In [72]:
pi = math.pi
pi

3.141592653589793

In [73]:
rel_btw_email_1_and_email_2 = np.arccos((dot_prod_email_1_and_email_2)/(mod_of_email_1 * mod_of_email_2))* (180/pi)
rel_btw_email_1_and_email_2

90.0

In [74]:
np.arccos(3/(np.sqrt(5)*np.sqrt(2)))*(180/pi)

18.434948822922017

In [75]:
dot_prod_email_1_and_email_3 = np.dot(email_1, email_3)
dot_prod_email_1_and_email_3

3

In [82]:
mod_of_email_3=calculate_mod(email_3)
mod_of_email_3

1.4142135623730951

In [84]:
mod_of_email_4=calculate_mod(email_4)
mod_of_email_4

1.7320508075688772

In [85]:
dot_prod_email_1_and_email_4 = np.dot(email_1, email_4)
dot_prod_email_1_and_email_4

3

In [80]:
rel_btw_email_1_and_email_3 =  np.arccos((dot_prod_email_1_and_email_3)/(mod_of_email_1 * mod_of_email_3))* (180/pi)
# returns 18.434948822922017
rel_btw_email_1_and_email_3

18.434948822922017

In [78]:
dot_prod_email_1_and_email_4 = np.dot(email_1, email_4)
dot_prod_email_1_and_email_4

3

In [86]:
rel_btw_email_1_and_email_4 =  np.arccos((dot_prod_email_1_and_email_4)/(mod_of_email_1 * mod_of_email_4))* (180/pi)
rel_btw_email_1_and_email_4

39.231520483592256

In [79]:
dot_prod_email_2_and_email_3 = np.dot(email_2, email_3)
dot_prod_email_2_and_email_3

0

In [87]:
rel_btw_email_3_and_email_4 =  np.arccos((dot_prod_email_3_and_email_4)/(mod_of_email_3 * mod_of_email_4))* (180/pi)
rel_btw_email_3_and_email_4

35.26438968275466

In [24]:
dot_prod_email_2_and_email_4 = np.dot(email_2, email_4)
dot_prod_email_2_and_email_4

1

In [25]:
dot_prod_email_3_and_email_4 = np.dot(email_3, email_4)
dot_prod_email_3_and_email_4

2